### ISSUE TITLE
Items move in grid when scrolling

### ISSUE THREAD

**Issue by peavers** [rintoj/ngx-virtual-scroller#270]
I have a standard column/grid layout, it all works however when scrolling past the buffered amount the items in the grid start to move along the grid one by one, like the index value is changing. 

Hopefully I've just not configured something correctly.  

Using a very basic example: 

```html
<div class="section">
  <div class="container">

    <virtual-scroller #scroll [parentScroll]="scroll.window" [items]="filteredList">

      <div class="columns is-multiline video-list">
        <app-video-card *ngFor="let item of scroll.viewPortItems" [video]="item" class="column is-3"></app-video-card>
      </div>

      <div *ngIf="loading">Loading...</div>

    </virtual-scroller>

  </div>
</div>
```

```javascript
@Component({
  selector: 'app-video-list',
  templateUrl: './video-list.component.html',
  styleUrls: ['./video-list.component.scss'],
})
export class VideoListComponent implements OnInit {

  public items: Video[];

  constructor(private data: DataService) {
  }

  public ngOnInit() {
    this.data.getVideos().subscribe(videos => {
      if (videos != null) {
        this.items = videos;
      }
    })
  }
}
```

```css
.scroll-window {
  width: 100%;
  height: 100%;
  max-width: 100vw;
  max-height: 100vh;
}

.video-list {
  height: 100px;
}
```
I have a suspicion my css is just wrong?

**Comment by speige** [comment]
Would you mind converting this to a stackblitz to help troubleshoot it easier? Thanks.

**Comment by peavers** [comment]
Sure: https://stackblitz.com/edit/angular-ctzu2i

If you watch a colour on the bottom row, then slowly scroll down you'll see it move to the left, scroll back up and it moves to the right...

**Comment by speige** [comment]
Change this line:
```
      <div class="columns is-multiline video-list">

```

To This:
```
      <div class="columns is-multiline video-list" #container>
```

Also, you can remove bufferAmount.

The reason is ngx-virtual-scroller has to measure the child items to know how big they are in order to do math on which items to render at each scroll position. It assume all children will be directly underneath it. If you have extra html wrapping your list of items, the #container templateRef is used to tell ngx-virtual-scroller where the child items are. You can read more about it in the docs, if you need further clarification.

That seemed to fix it for me on your stackblitz. Closing. Please re-open if you continue to have issues.
