### ISSUE TITLE
Can't get window scroll to work

### ISSUE THREAD

**Issue by fredericojesus** [rintoj/ngx-virtual-scroller#271]
Hi,

I have an example using stackblitz: https://stackblitz.com/edit/angular-r3jet7

Window scroll is not working and I can't figure out why. 
The items are being all rendered at once.

Does anyone knows what the problem is ?

**Comment by speige** [comment]
As per the documentation at https://github.com/rintoj/ngx-virtual-scroller you must have a set width/height for the ngx-virtual-scroller component, otherwise it'll stretch to contain all child items, which you don't want. However, if you're using a parent scrollbar (or window scrollbar) that parent element needs to have the set width/height instead of the ngx-virtual-scroller component.

So, in your stackblitz, something like this (in styles.css) will fix it:
```
body {
  width: 200px;
  height: 500px;
}
```

You'll have to determine those sizes based on your particular app. The width is probably only necessary for horizontal scrolling & the height probably only necessary for vertical scrolling, but it's hard to be definitive without looking at your exact app, so the documentation says to specify both, just to be safe. You can experiment in your app & see what works.

Closing ticket. Please re-open if you continue to have issues.

**Comment by fredericojesus** [comment]
Thanks @speige.
Yes, it was missing height: 100% on html tag not on body.

Sorry to bother.
