### ISSUE TITLE
Virtual Scroller shows no items in OnPush components

### ISSUE THREAD

**Issue by konrad-garus** [rintoj/ngx-virtual-scroller#273]
If the component containing virtual-scroller uses OnPush, then the scroller shows no items. To reproduce, just set {{changeDetection: ChangeDetectionStrategy.OnPush}} on {{VerticalListComponent}}. The result looks like the attached picture.

Is this a bug, or by design? Do I have to always use virtual scroller with default change detection strategy - and why? 

![image](https://user-images.githubusercontent.com/242481/49148319-58817580-f307-11e8-93ef-1a39e3c67f54.png)

**Comment by speige** [comment]
It does work, but requires a bit of extra work. 

OnPush means the consuming app is taking responsibility for telling Angular when to run change detection rather than allowing Angular to figure it out itself. This is much faster (& I highly recommend it for complex apps that need speed), however it's much harder for the programmer because you have to code things differently (avoid mutating state on bound properties & manually running change detection if you do mutate state).

I coded a complex app which was really slow, but after converting *EVERY COMPONENT* to use OnPush it's blazing fast. However, it was a pain in the butt to add a manual change detection in every spot where I mutated state. I still highly recommend it, but it's not easy :)

Here's a working version of vertical-list.component.ts
```
import { Component, Input, OnChanges, ViewChild } from '@angular/core';
import { VirtualScrollerComponent } from 'ngx-virtual-scroller';
import { ListItem, ListItemComponent } from './list-item.component';
import { ChangeDetectionStrategy, ApplicationRef, ChangeDetectorRef } from "@angular/core";

@Component({
  selector: 'vertical-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <button (click)="sortByName()">Sort By Name</button>
    <button (click)="sortByIndex()">Sort By Index</button>
    <button (click)="reduceListToEmpty()">Reduce to 0 Items</button>
    <button (click)="reduceList()">Reduce to 100 Items</button>
    <button (click)="setToFullList()">Revert to 1000 Items</button>
    <button (click)="scroll.scrollToIndex(50)">Scroll to index 50</button>
    <button (click)="scroll.scrollToPosition(1500)">Scroll to position 1500</button>
    <button (click)="randomHeight = !randomHeight">Toggle Random Height</button>
    <button *ngIf="randomHeight" (click)="ListItemComponent.ResetSeed();">Re-Randomize Item Sizes</button>
    <button *ngIf="randomHeight" (click)="scroll.invalidateAllCachedMeasurements();">Invalidate cached measurements</button>

    <div class="status">
        Showing <span>{{scroll.viewPortInfo.startIndex}}</span>
        - <span>{{scroll.viewPortInfo.endIndex}}</span>
        of <span>{{filteredList?.length}}</span>
      <span>({{scroll.viewPortItems?.length}} nodes)</span>
      <span>[scrollStartPosition: {{scroll.viewPortInfo.scrollStartPosition}}px, scrollEndPosition: {{scroll.viewPortInfo.scrollEndPosition}}px, maxScrollPosition: {{scroll.viewPortInfo.maxScrollPosition}}px ]</span>
    </div>

    <virtual-scroller #scroll (vsChange)="queueChangeDetection();" (vsUpdate)="queueChangeDetection();"
      [enableUnequalChildrenSizes]="randomHeight"
      [items]="filteredList">

      <list-item [randomHeight]="randomHeight" *ngFor="let item of scroll.viewPortItems" [item]="item"> </list-item>

    </virtual-scroller>
  `
})
export class VerticalListComponent implements OnChanges {
  @Input()
  public items: ListItem[];

  constructor(private applicationRef: ApplicationRef, private changeDetectorRef: ChangeDetectorRef) {
  }
  
  public ListItemComponent = ListItemComponent;
  public randomHeight = false;
  public filteredList: ListItem[];

  public reduceListToEmpty() {
    this.filteredList = [];
  }

  public reduceList() {
    this.filteredList = (this.items || []).slice(0, 100);
  }

  public sortByName() {
    this.filteredList = [].concat(this.filteredList || []).sort((a, b) => -(a.name < b.name) || +(a.name !== b.name));
  }

  public sortByIndex() {
    this.filteredList = [].concat(this.filteredList || []).sort((a, b) => -(a.index < b.index) || +(a.index !== b.index));
  }

  public setToFullList() {
    this.filteredList = (this.items || []).slice();
  }

  public ngOnChanges() {
    this.setToFullList();
  }
  
  public queueChangeDetection(): void {
	this.changeDetectorRef.markForCheck(); // marks self for change detection on the next cycle, but doesn't actually schedule a cycle
	this.queueApplicationTick();
  }
  
  public queueApplicationTick(): void { //note: this method should be debounced to ~50ms for performance reasons so multiple change detection cycles are merged into 1.
	if (this.applicationRef['_runningTick']) {
		return;
	}

	this.applicationRef.tick();
  }
}
```

I have 2 methods which schedule change detection. You should make these global/static methods that are shared across your entire app. Whenever you mutate state on any component, that specific component should call queueChangeDetection using its injected ChangeDetectorRef. Note that ApplicationRef can be injected separately into each component or it can be injected 1x in your main entry component & shared statically. However, ChangeDetectorRef is component specific, you must use the instance that was injected into the specific component that has mutated its state.

Notice that I suggest doing a debounce on queueApplicationTick. I've left that out because I'm not sure what library your app is using & how you prefer to debounce.

If you don't have this available in a current library that your app is consuming, here's an implementation:
```
public class Util {
	public static debounce(func: Function, wait: number): Function {
		const throttled = this.throttleTrailing(func, wait);
		const result = function () {
			throttled['cancel']();
			throttled.apply(this, arguments);
		};
		result['cancel'] = function () {
			throttled['cancel']();
		};

		return result;
	}
}

  public queueApplicationTick: ()=> void = Util.debounce(() => {
	if (this.applicationRef['_runningTick']) {
		return;
	}

	this.applicationRef.tick();
  }, 50);
```

This is all Angular/OnPush specific stuff, nothing related to ngx-virtual-scroller.

If this is confusing, you'll need to do a lot of research on your own about how OnPush works or you'll need to stick with the default change detection strategy.

I did notice that this could be slightly easier on the consumer of ngx-virtual-scroller. I can add a changeDetectorRef.markForCheck() call in virtual-scroller.ts immediately before vsChange/vsUpdate are called & it'll solve this problem. Angular is already calling applicationRef.tick() because I'm running that code inside an Angular zone. I'll commit this & publish it to NPM. It should make it slightly easier for OnPush users & shouldn't hurt anyone using the default change detection strategy. Thanks for the suggestion!

I think I'll also copy this entire comment into the readme to help people understand OnPush better.

Thoughts?

Hope this helps.

**Comment by speige** [comment]
This has been committed & published to npm. Also, the readme has been updated with general advice about OnPush strategy.

Closing this issue. Please re-open if you continue to have issues.

**Comment by konrad-garus** [comment]
Thanks for looking into this. Indeed, looks like I'm in for some research.
