### ISSUE TITLE
Question: visible items

### ISSUE THREAD

**Issue by horba** [rintoj/ngx-virtual-scroller#285]
Good day,

We use your scroll in our project and it's real fast and useful. But we have requirement in different times scroll to item if it is only invisible, so scrollTo() doesn't help because it scroll item to top in any case. And it's critical for our customer, unfortunately. Please, can you take me advice how can I check if item is visible.

**Comment by speige** [comment]
You can use the viewPortInfo property which has type IPageInfo. It has the properties you need to determine which items are currently visible.

You could also do viewPortItems.indexOf()

One caveat is sometimes an item will be in the DOM but only partially visible because it's partially scroll out of view. If you need to account for this situation, you'll need to write custom javascript to check pixels, I can't give advice on how to do this, you'll need to research it on your own.

If you have questions, please read the documentation, it's very thorough. If you still can't figure it out, feel free to re-open issue.

**Comment by horba** [comment]
Thanks,
Actually, viewPortInfo doesn't have enough information. I tried it earlier, bur viewport has some boost in bottom, so item can be in viewport but it isn't visible at all, not partially. 
In any case, thank you
