### ISSUE TITLE
childHeight prevents jumps when changing chunks with margin bottom (or top)

### ISSUE THREAD

**Issue by ranbuch** [rintoj/ngx-virtual-scroller#286]
I found that when having items with margin bottom the scroller jumps in the exact amount of pixels that I use for margin bottom.

Specifying `childHeight`, that is the item height + margin bottom is solving this issue.

I saw that `childHeight` is `(DEPRECATED)` so I'm assume you will soon stop supporting this attribute.

Please continue supporting `childHeight` or calculate `childHeight` with the margin top + bottom.

**Comment by speige** [comment]
Could you create a stackblitz demonstrating this? The reason childHeight is deprecated is because the code should auto-calculate the item sizes now.

**Comment by whyboris** [comment]
I have for over a year [been using](https://github.com/whyboris/Video-Hub-App) this library, and to get around the issue you describe I have:
```html
[childHeight]="imgHeight + 20"
```
Where the 20px is the amount I experimentally determined that was needed.

**Comment by whyboris** [comment]
I have a rather complex setup -- a vertical scrolling gallery showing several items per row and many rows at a time. I set it up back when this repository was `ng2-virtual-scroller` when variable height was not available. It's possible that there's a way to avoid using my complicated setup now.

Not to hijack the thread, but I have not been successful in getting an even-more-complicated setup: allowing for a 100% width div to appear sometimes, breaking up the flow of displayed items: https://github.com/whyboris/Video-Hub-App/pull/123#issuecomment-457931821

I have a branch (`auto-virtual-scroller`) where this complicated setup works great, but it does only because it displays _all_ the elements (without hiding any) - thereby negating the point of a _virtual_ scroller. Perhaps it was a problem with my setup, or just the scenario I want to fit into this library doesn't work.

Huge _thank you_ to rintoj for creating and to others (like you speige) for maintaining this excellent library 🙇 -- I tried the _Angular 7_ ScrollingModule (`import { ScrollingModule } from '@angular/cdk/scrolling';`) as competition, but it couldn't do what _ngx-virtual-scroller_ is doing 💯

**Comment by emko** [comment]
yea i use [childHeight]= as well because without it scrolltoindex doesn't take into account the margin top of the item unless i am doing something wrong?

**Comment by georgegrafos** [comment]
Hi, I believe my issue is also related to this.

I am using scrollInto with enableUnequalChildrenSizes="true". My items have a margin-bottom of 15px. Under these conditions, the viewport isn't properly scrolled so the item is aligned to the top. I also notice some jittering at times as I scroll manually. However, when removing the margin-bottom, everything works perfectly.

**Comment by Floaz** [comment]
I ran into the same problem. I'm also using `enableUnequalChildrenSizes="true"`.
I solved it by using `padding-bottom` instead of `margin-bottom`.
Maybe the calculation of the children size does not respect the margin.

**Comment by speige** [comment]
ngx-virtual-scroller uses getBoundingClientRect() for its measurements. This function doesn't include margin, only padding/border.

This seems like a bug to me & I'd like to fix it. However, when I've tried switching from padding to margin in my projects, surprisingly everything still seems to work fine. Could someone please create a stackblitz that demonstrates the issue caused by margin so after I code a fix I can test to ensure it resolves the problem?

Thanks.

**Comment by whyboris** [comment]
Thank you @Floaz for mentioning that switching from `margin` to `padding` may solve some scrolling issues 🙇 -- I can confirm that in my project *Video Hub App* this simple change made scrolling better: https://github.com/whyboris/Video-Hub-App/pull/172

**Comment by speige** [comment]
This should be fixed now & published to npm v2.0.9. Please try it (with margin on your element rather than the padding workaround) & see if it works. You could also try it with both padding & margin.

Closing this as I believe it's fixed. Please re-open if you continue to have issues.

**Comment by whyboris** [comment]
Thank you @speige 🥇 
For those curious, here's the link to the code changes:
https://github.com/rintoj/ngx-virtual-scroller/commit/b47bee32c4fe919615df776b0158969b3d7f35ba
