### ISSUE TITLE
[Question] How to proper set parent scrolling?

### ISSUE THREAD

**Issue by wunaidage** [rintoj/ngx-virtual-scroller#290]
Hi Team/Rinto, 
At first thank you for developing such great library. 
Right now I'm trying to integrate it with my project and use parent scrolling. 
I have a complex list contains more than 1000 home grown component, if fully rendered it will freeze the page. I followed the demo page and found that only when I give virtual scroller tag a certain height or max-height, the parent scrolling will start to work. However, by doing so, the virtual scrolling part will overlaps the following element after the certain height reached. I studied the parent scrolling demo page and the source code. It seems you did not set a certain height on the virtual scroller tag and still you can render 10 item at a time and also have a footer. How did you do it?

**Comment by speige** [comment]
Without parentScroll, the virtual-scroller component must have a fixed height. With parentScroll, the parent element needs to have a fixed height. This is stated in the documentation & the demo follows this pattern as well. If you use your browser to inspect the demo styles you'll see the body/html tags have 100% height caused by blog.css file.

I'm not sure what would cause it to overlap with other elements. It's probably something wrong with your html/css. If you can create a stackblitz to demonstrate your issue, we can help troubleshoot it.

**Comment by wunaidage** [comment]
@speige thank you very much. I find that I need to set the height html and it will work. body height somehow is not working. You saved my day!

**Comment by rahul4850** [comment]
Yes, We have to add height 100% on HTML tag to make it work.
