### ISSUE TITLE
Initial Loading Issue when delay in getting data

### ISSUE THREAD

**Issue by skreel** [rintoj/ngx-virtual-scroller#294]
I followed the example for loading in chuncks ( https://rintoj.github.io/ngx-virtual-scroller/samples ). I made it so the fetchNextChunk function iterates from the skip to the limit passed into it. See code below. Everything works fine unless I add in an artificial timeout to simulate real world delay when calling a remote api. Without the delay, the list loads and displays 0 through infinity as you scroll. When I add the delay the list shows 0 through 199, then 0 through 199 again and a third time 0 through 199. Then it will show 600 and the next 200 items and things continue fine as you scroll. If you create a really large delay, scroll to the bottom, then scroll up and back to the bottom, the items will repeat again too. I apologize if I'm missing something obvious.

  protected buffer: ListItem[] = [];
  protected loading: boolean;

  protected fetchMore(event: ChangeEvent) {
    if (event.end !== this.buffer.length - 1) return;
    this.loading = true;

    this.fetchNextChunk(this.buffer.length, 200).then(chunk => {
      this.buffer = this.buffer.concat(chunk);
      this.loading = false;
    }, () => this.loading = false);
  }
  
  protected fetchNextChunk(skip: number, limit: number): Promise<ListItem[]> {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        let items: ListItem[] = new Array();
        for (let i: number = skip; i < (skip + limit); i++) {
          items.push({
            id: i,
            name: "name" + i
          });
        }
        resolve(items);
      }, 1000);

    }); 
  }

**Comment by skreel** [comment]
Here is a link to a stackblitz showing the issue: https://angular-mrejdh.stackblitz.io

**Comment by speige** [comment]
The code in the actual ngx-virtual-scroller component is solid. However, the "samples" are not all solid. Some of the samples have a very naive implementation that you'll need to improve upon for your specific application.

First of all, fetchNextChunk is creating fake items, most likely your real code will need to download via ajax from a web api.

The other issue with your code is that vsChange occurs A LOT, so your fetchMore code needs to be smart about not re-adding the same items. If you put a breakpoint in fetchMore you'll notice that it calls this.fetchNextChunk(this.buffer.length, this.bufferSize); Because fetchNextChunk is async it'll get called multiple times before this.items.length has changed. So, it keeps getting called with identical parameters & keeps appending the same fake items.

You'll need to come up with your own javascript to account for this. ngx-virtual-scroller doesn't know how your getting the items from your api so it can't control throttling or caching or preventing an identical api from being called 2x.

Good luck & if you come up with some code that you want to submit to improve the sample I'm happy to accept a pull request.
