### ISSUE TITLE
Retain component state?

### ISSUE THREAD

**Issue by Nirco96** [rintoj/ngx-virtual-scroller#296]
Hey, the component I use with the scroller are expendable on a button click, there's a boolean field on the component which states whether the component is expanded (more-info-like expansion) or not. My problem is that whenever I scroll far enough from the expanded component (boolean field is now true), and scroll back to it, the component is now rendered as not expanded. This boolean field is exclusive for the view alone, and I dont feel comfortable with the model itself passed in the *ngFor holding it, since it makes no sense as it is view only. Is there a solution for this? What could be a possible workaround if not?

Thanks!

**Comment by speige** [comment]
virtual-scroller essentially uses *ngIf to remove items that are scrolled out of view. This is what gives the performance benefits compared to keeping all the off-screen items in the DOM.

Because of the *ngIf, Angular completely forgets any view state. If your component has the ability to change state, it's your app's responsibility to retain that viewstate in your own object which data-binds to the component.

example:
```
<virtual-scroller #scroll [items]="items">
    <my-custom-component [expanded]="item.expanded" *ngFor="let item of scroll.viewPortItems">
    </my-custom-component>
</virtual-scroller>
```

If you don't like putting "view" state into your model, I suggest creating a new object that you think of as a ViewModel. Which has structure { view: any, model: any  }

It would be a good feature of ngx-virtual-scroller to have the ability to automatically retain the component's view state when the control is removed. However, I'm not sure if/how this is possible. It'd probably require a lot of research into Angular internals & may not be possible because component view state is very specific to each application. However, if you're interested in building this feature, please make an attempt to code it & submit a pull request. Thanks :)

Closing.
