### ISSUE TITLE
Is this repo still useful after virtual-scroll beeing built-in from angular 7 cdk ?

### ISSUE THREAD

**Issue by amineparis** [rintoj/ngx-virtual-scroller#303]

**Comment by mikemichaelis** [comment]
I haven't found a way to do multiple columns with the material 7 virtual-scroll so I would say that yes this repo has functionality I didn't find in material 7 vs.  I may be wrong though.

**Comment by speige** [comment]
Currently, this library has many extra features that the CDK doesn't have. Long-term hopefully CDK will become better & this one will be retired, because we don't have the resources to maintain it indefinitely :)

**Comment by mikemichaelis** [comment]
Yes thank you very much as I am currently still using this code.  The CDK did not have the functionality I needed.  Thank you very much for this work!

Get BlueMail for Android<http://www.bluemail.me/r?b=14726>
On Apr 5, 2019, at 5:03 PM, Devin Garner <notifications@github.com<mailto:notifications@github.com>> wrote:

Currently, this library has many extra features that the CDK doesn't have. Long-term hopefully CDK will become better & this one will be retired, because we don't have the resources to maintain it indefinitely :)
