### ISSUE TITLE
getting Namespace ''*'' has no exported member 'Tween'.

### ISSUE THREAD

**Issue by indraraj26** [rintoj/ngx-virtual-scroller#304]
Dear Rintoj,

Error: 
Typescript Error
Namespace ''*'' has no exported member 'Tween'.
/node_modules/ngx-virtual-scroller/dist/virtual-scroller.d.ts
protected previousViewPort: IViewport;
protected currentTween: tween.Tween;
protected cachedItemsLength: number;

 "ngx-virtual-scroller": "^1.0.16",
 "ionic-angular": "3.9.2",

Even i have added this in package.json "@types/tween.js": "^16.6.1" but still i am getting the same error.

**Comment by indraraj26** [comment]
Dear @rintoj , 

Please would you look into this issue? 
Thank you

**Comment by speige** [comment]
This issue has been reported many times. It seems to be related to specific projects because it doesn't affect most people. Please read through past closed issues to find the resolution. If you still can't find it, you'll need to use google/stackoverflow.

If you're able to find a permanent fix, please submit a pull-request. However, as most people don't have this issue, I don't think it's a bug in the library, but an issue with your project's code.

**Comment by speige** [comment]
I've re-arranged the publish format to prepare for ivy support. In the process I believe I may have fixed the tween issue. Can you re-test with the latest version on npm 2.0.4 ?

**Comment by indraraj26** [comment]
wait let me try will get back to you. 
Thank you.
