### ISSUE TITLE
Typo in Loading In Chunks example?

### ISSUE THREAD

**Issue by tcuje** [rintoj/ngx-virtual-scroller#320]
I tried the loading in chunks example here: https://github.com/rintoj/ngx-virtual-scroller#loading-in-chunks

My IDE tells the me that scrollItems is undefined, yet the view shows some items on first load, but then the views and scrollbar "shrink" after each load and gets some ugly whitespace at the end, where no items are displayed at all.

Is it correct that scrollItems seems to be undefined? Any ideas/hints regarding the whitespace?

**Comment by speige** [comment]
You're correct, that example is old/incorrect.

There is a better example here:
https://github.com/rintoj/ngx-virtual-scroller/blob/master/demo/src/app/lists/list-with-api.component.ts
https://github.com/rintoj/ngx-virtual-scroller/blob/master/demo/src/app/lists/list-with-api.scss

You can see it in action here:
https://rintoj.github.io/ngx-virtual-scroller
Click on samples then scroll down to loading in chunks.

Thanks foe pointing this put. I'll update the readme soon.

**Comment by tcuje** [comment]
Seems like html table is not supported anymore? Or at least I can't find it.

**Comment by speige** [comment]
It's still supported.
https://github.com/rintoj/ngx-virtual-scroller#with-html-table

The readme is getting long, I should probably create a table of contents :)

**Comment by speige** [comment]
HTML Tables are still supported. You can see it working at https://rintoj.github.io/ngx-virtual-scroller
Click on "Samples" then scroll down to the "With Table" section.

I haven't tried combining the two samples (loading in chunks + with table), but I can't think of any reason why they wouldn't work together.

If you can't get it working, please create a stackblitz to help in troubleshooting.

**Comment by speige** [comment]
I've updated the readme to use the new syntax for loading with chunks. It was a minor change, the old code actually should have worked, the error you saw was probably just a warning.

At the top of the readme there is a "Usage" section.
Preferred option:
```
<virtual-scroller #scroll [items]="items">
    <my-custom-component *ngFor="let item of scroll.viewPortItems">
    </my-custom-component>
</virtual-scroller>
```
option 2: note: viewPortItems must be a public field to work with AOT
```
<virtual-scroller [items]="items" (vsUpdate)="viewPortItems = $event">
    <my-custom-component *ngFor="let item of viewPortItems">
    </my-custom-component>
</virtual-scroller>
```

The loading with chunks example was using option #2. It's correct that the property scrollItems was undefined, however it should have still worked fine, because javascript is dynamic, so it'll auto-create it the first time a value is assigned. However, that's confusing to VisualStudio & AOT, so it's best to explicitly define the property. That specific example didn't explain that because it's explained at the top of the readme. 

That was the old syntax which isn't preferred. The updated syntax doesn't require creating a new property.
