### ISSUE TITLE
Use with bootstrap responsive design

### ISSUE THREAD

**Issue by Exocomp** [rintoj/ngx-virtual-scroller#321]
How would I set this up with a bootstraps responsive design?

For example:
```
<div class="row">
	<div class="col-lg-3 col-md-3 col-sm-4 col-xs-6 col-6" *ngFor="let item of items; let i = index">
		<img src="{{item.url}}">
	</div>
</div>
```

So basically image are loaded horizontally next to each other and wrap down the viewport and resizing the viewport will change the size of columns.

**Comment by speige** [comment]
Sorry, we don't have the resources to answer these type of questions. You can research it on your own or try stackoverflow. If you come up with a solution, feel free to update the issue for future developers.

Good luck!

**Comment by Exocomp** [comment]
I created a post in stackoverflow @ https://stackoverflow.com/questions/55753680/angular-virtual-scroll-with-bootstrap-responsive-design

**Comment by speige** [comment]
Maybe I misunderstood your question.

ngx-virtual-scroller does support wrapping.
You can see an example here:
https://rintoj.github.io/ngx-virtual-scroller
click samples & scroll down to "with multiple columns".
You can see the sourcecode here: https://github.com/rintoj/ngx-virtual-scroller/tree/master/demo/src

GitHub Issues are for fixing problems with the library. If you find a broken feature, we're happy to fix it. However, issues are not for asking "how" to code something. Every project is different & we don't have the resources to help you figure out how to code your project.

You specifically mentioned bootstrap. I don't know the internals of bootstrap css very well, but I think "row" classes have display: flex; & the col-* use a different flex-basis % of the viewport width based on the # columns (% should auto-adjust for devices screen size). I'm not sure how that would interact with ngx-virtual-scroller & I'm not sure where you'd add the row/col classes, you can try to figure it out, but it may or may not work as expected & it's not a scenario we specifically support.

My suggestion would be to not use any bootstrap classes for this partical piece of your html. Use a normal vertical ngx-virtual-scroller, use style display: inline-block; on your child items (which will make them layout horizontally). ngx-virtual-scroller will automatically wrap them. The tricky thing is you will need to determining the width of each child-item via custom css since you're not letting bootstrap automatically do it. You'll need to figure this portion out on your own, however here's a suggestion:

```
// Extra-Small devices (portrait phones, less than 576px)
my-child-item {
   width: 50vw;
}

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { 
my-child-item {
   width: 33vw;
}
}

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) {
my-child-item {
   width: 25vw;
}
}

// Large devices (desktops, 992px and up)
@media (min-width: 992px) {
my-child-item {
   width: 25vw;
}
}

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) {
my-child-item {
   width: 25vw;
}
}
```


I guessed on the widths based on your original classes. Essentially twitter has 12 max columns so col-md-3  means on a medium screen each item should take up 3/12 columns (or 25% of the available width). I used "vw" as viewportwidth, but that may not work if your scroller isn't full-screen. In that case you could try  25% instead of 25vw, or use hard-coded px for your widths.

That's all the help I can give. Good luck!

**Comment by Exocomp** [comment]
@speige that's awesome, thanks for the additional info. Your work in this library is awesome and is much appreciated.
