### ISSUE TITLE
Inject Ionic 4 Dom Controller Write for performance

### ISSUE THREAD

**Issue by tmk1991** [rintoj/ngx-virtual-scroller#329]
Hello - 

While it's not necessarily the responsibility of this repo, I have a question about how to extend its usage. 

In ionic 4 there is a Dom Controller ( https://github.com/ionic-team/ionic/blob/master/angular/src/providers/dom-controller.ts) 

It helps control writing events for performance. I'm wondering how i'd contain the events from when `ngx-virtual-scroller` writes new records? Would I:

- use vsUpdate event and contain updating the public variable for `virtual-scroller`?
- use vsUpdate event with `[executeRefreshOutsideAngularZone]="true"` and wrap the `"changeDetectorRef.detectChanges();"` with the Ionic `DomController` `write()` in a controller function?
- some other way...

The reason I ask is for performance reasons. In Webkit view when one of my virtual items contains image or video tags, my scroller goes haywire and flickers. I use trackBy and it helped a lot but still not where it needs to be.
`<div class="infinite-item" *ngFor="let d of scroll.viewPortItems; trackBy: trackByIdx">`

Thanks again for this great component. Better than CDK scroll and Ionic's own Virtual Scroll.

**Comment by speige** [comment]
I believe you're looking at the problem from the wrong perspective. The problem isn't ngx-virtual-scroller, the problem is your code & the components you're rendering inside the scroller. Don't be offended, this is an easy mistake almost all Angular developers make, I'll explain it shortly.

ngx-virtual-scroller is extremely performant, there is no wrapper you can put around it to fix it. 

[executeRefreshOutsideAngularZone]="true" was a very bad hack from a pull-request, I should probably remove it, it provides no value & actually causes major bugs. Essentially it completely disables any change detection caused by ngx-virtual-scroller. This means the scroller will be fast, yet completely broken, unless something else causes change detection to run, in which case it scroller will work but still be slow. Literally no point.

I'm not an expert on Ionic or DomController, however I don't think it'll help with this particular problem. It seems like the idea behind DomController is to make Dom changes in batches to prevent layout thrashing.  Angular's change detection runs inside the method ApplicationRef.tick(), I believe it already batches Dom changes.

Without looking at your code, I'm going to assume this is your real problem:
By default Angular does *automatic* change detection. This means that it's constantly checking every variable on every component in your entire app to see if any values have changed. This change-detection-thrashing is your real issue. Angular does this to make coding easy, but they know it intentionally creates very slow apps. For performant apps, they recommend using OnPush for everything.

I explain this in-depth (& my suggested solution) here - https://github.com/rintoj/ngx-virtual-scroller#angular-onpush-detection-strategy---general-performance-advice-not-specific-to-ngx-virtual-scroller

Essentially you need to convert *any* custom components rendered underneath ngx-virtual-scroller to use the OnPush change-detection-strategy. This includes any sub-children as well, not just the main children. This is a relatively easy code change & scrolling *should* be instantly fast. However, the downside is those components will suddenly not work correctly (meaning they render stale data, etc). The hard part will be to find anywhere in the code that mutates state & manually calling changeDetection. In this way you'll remove the thrashing because changeDetection will only execute when actually needed.

Because finding all the places where state is mutated is difficult, I suggest only converting the slow components at first & eventually converting all components as you have time.

The readme link I provided has example code for doing something similar to what DomController does (combine multiple manual change-detection cycles into 1 to avoid thrashing), It'll make your OnPush conversion easier & will avoid extra cycles. You should be able to copy/paste that into your app to get a head start.

I'm going to close this as it appears to be a question, not an issue, & is probably caused by user error. If after you've converted to OnPush you're still having performance problems (which I would be shocked), feel free to re-open the issue & I'll investigate it further with you.

P.S. I have an app which uses images under ngx-virtual-scroller with no performance issues at all. The only concern I have with videos is, make sure you don't actually "load" the video (thumbnail is fine) unless they actually click a "play" button. If scrolling started thousands of videos buffering that'd be a major performance issue.

**Comment by tmk1991** [comment]
Thanks! This was exactly what I had to hear (no offense taken). I will give it a shot!
