### ISSUE TITLE
Why executeRefreshOutsideAngularZone is deprecated?

### ISSUE THREAD

**Issue by splincode** [rintoj/ngx-virtual-scroller#339]
We use flag executeRefreshOutsideAngularZone and and our application is much faster

```
<virtual-scroller
    #scroll 
    [executeRefreshOutsideAngularZone]="true"
    (vsChange)="cd.detectChanges()"
>...
</virtual-scroller>
```

Why is this property obsolete?

**Comment by speige** [comment]
Because I believe it's the incorrect way to get a performance boost & is buggy. However, I'm not planning to remove it immediately, just discouraging future coders from using it.

I marked it deprecated to see how many coders would complain to see how many projects are currently using it. I'm only aware of 1 project using it.

I don't want to have a documented api for a feature that I disagree with. However, I think there's a way to achieve the same result without making it an officially supported feature.

If you make a "wrapper" module around VirtualScrollerModule, you can change the injector to use a "NoOp" version of ngZone only for virtual scroller.

Example:
virtualScrollerWrapper.module.ts:
```
import { ComponentFixtureNoNgZone } from '@angular/core/testing';
import { NgModule } from "@angular/core";
import { VirtualScrollerModule } from 'ngx-virtual-scroller';

@NgModule({
    imports: [
        VirtualScrollerModule
    ],
    providers: [
        { provide: ComponentFixtureNoNgZone, useValue: true }
    ],
    entryComponents: [],
    declarations: [],
    exports: [VirtualScrollerModule],
    bootstrap: []
})
export class VirtualScrollerModuleWrapper {
    constructor() {
    }
}
```

Could you test this in your project & see if it achieves the same result?

**Comment by splincode** [comment]
If you use ComponentFixtureNoNgZone, then it tightens additional dependencies from the testing package, and the bundle weighs a lot.  It is also very strange in production to use the functionality intended for testing.

**Comment by nickbullock** [comment]
Local branch change detection is cheaper than AppRef.tick even if all of your components have OnPush strategy. I think it is Angular/NgZone code overhead. 
They failed to make the change detection mechanism from the root of the tree as fast as in React.js.
It is still like $scope.digest() vs $rootScope.digest().
This is the only reason this flag is useful.

**Comment by speige** [comment]
I understand the bundle size issues since tree-shaking is bad with Angular. As an alternative to ComponentFixtureNoNgZone, you could also use:
```
import { NgModule } from "@angular/core";
import { VirtualScrollerModule } from 'ngx-virtual-scroller';
import { NgZone, ɵNoopNgZone as NoopNgZone } from '@angular/core'

@NgModule({
    imports: [
        VirtualScrollerModule
    ],
    providers: [
        { provide: NgZone, useClass: NoopNgZone }
    ],
    entryComponents: [],
    declarations: [],
    exports: [VirtualScrollerModule],
    bootstrap: []
})
export class VirtualScrollerModuleWrapper {
    constructor() {
    }
}
```
NoopNgZone has a weird unicode symbol (barred-o) because Angular hasn't made it an "officially documented" api. If you don't like that, you could copy/paste just that class into your code:
```
class NoopNgZone implements NgZone {
  readonly hasPendingMicrotasks: boolean = false;
  readonly hasPendingMacrotasks: boolean = false;
  readonly isStable: boolean = true;
  readonly onUnstable: EventEmitter<any> = new EventEmitter();
  readonly onMicrotaskEmpty: EventEmitter<any> = new EventEmitter();
  readonly onStable: EventEmitter<any> = new EventEmitter();
  readonly onError: EventEmitter<any> = new EventEmitter();
 run(fn: () => any): any { return fn(); }
 runGuarded(fn: () => any): any { return fn(); }
 runOutsideAngular(fn: () => any): any { return fn(); }
 runTask<T>(fn: () => any): any { return fn(); }
}
```

I only suggested ComponentFixtureNoNgZone because it is officially documented, whereas ɵNoopNgZone isn't.

I believe all 3 of these examples are the same as disabling NgZone from the injector of VirtualScroller, which should be identical as the executeRefreshOutsideAngularZone flag.

I agree that Angular's ChangeDetection could be faster, but with OnPush it should be "fast enough".
I'd like to see an example where all components are using OnPush & it's still slow enough that this flag is necessary.



In my testing, using the executeRefreshOutsideAngularZone (or disabling ngZone) causes bugs in ngx-virtual-scroller where components aren't updated & render stale views. I don't feel comfortable making a public flag which has known bugs, even though it gives performance benefits. This will cause headaches for other users of ngx-virtual-scroller who don't understand the flag & will cause the library maintainers to have to respond to issues that should have never existed.

For this reason the flag is listed as deprecated & I've removed any explanation of the flag from the readme. I believe if a coder wants to intentionally "break the warranty" of the library, they should do it in their own code (by monkey-patching the code, injecting NoopNgZone, or branching the repo), that way they're taking on the risk of those decisions themselves, rather than adding bad-practice code as an official api to the library which becomes a trap for all library users to use the bad-practice code. If this was a common request, I would reconsider, but I believe it's only 1 project, & I haven't seen proof that OnPush can't fix the issue.

**Comment by splincode** [comment]
When I tried your approach, in this case, my application stopped working completely (auto detect changes) every where!

```ts
import { NgModule, NgZone, ɵNoopNgZone as NoopNgZone } from '@angular/core';
import { VirtualScrollerModule } from 'ngx-virtual-scroller';

@NgModule({
    imports: [VirtualScrollerModule],
    providers: [{ provide: NgZone, useClass: NoopNgZone }],
    exports: [VirtualScrollerModule]
})
export class VirtualScrollerModuleWrapper {}
```

my-table.module.ts

```ts
@NgModule({
  imports: [VirtualScrollerModuleWrapper],
  ...
})
export class MyTableModule {
}
```

Initially, I thought that this approach is limited only to the module that we use, but in fact, in the application, ngZone are disabled everywhere in the application.

**Comment by speige** [comment]
@splincode You're right, my mistake.

There should be a way to make it only affect just VirtualScroller, but I'm not sure how :(

**Comment by speige** [comment]
I've been thinking a lot about this & I've decided to keep executeRefreshOutsideAngularZone as an officially supported API.

My initial fear with executeRefreshOutsideAngularZone was because I thought it caused major bugs across my entire app. I didn't want to deal with tech support if other developers started using the flag. However I recently realized it was actually a bug in my own manual change detection & executeRefreshOutsideAngularZone was not the root cause.

I still believe OnPush is the ideal approach, but it's also much harder to implement. Although executeRefreshOutsideAngularZone "easier" to implement, I don't want developers to make the same mistakes with manual change detection that I did. For this reason, I've added an explanation to the ReadMe which explains how to do it properly. Hopefully this will minimize any issues related to executeRefreshOutsideAngularZone.

I think executeRefreshOutsideAngularZone is a good initial approach for users to get a quick performance boost before they're ready to move to full-appp OnPush. Thanks for submitting the initial idea & PR & thanks for helping me to understand it. Sorry I was slow/stubborn :)
