### ISSUE TITLE
ViewChildren - scroller element is protected no access to nativeElement.id

### ISSUE THREAD

**Issue by casper5822** [rintoj/ngx-virtual-scroller#340]
Hello,
if i have many scrollers and use ViewChildren to filter one of them:

Tipically i assign an id on the html element end then access within item.element.nativeElement.id.
But in the virtualscroller component, the element is protected.
So is there any way to filter a scroller in a viewchildren context using an id?

Thank you

**Comment by speige** [comment]
I don't think there's a reason to change it from protected to public, because there's already a way to access it built into Angular. I think you want the use the "read" property of @ViewChildren.

This gets the default injectable related to the selector (In this case a reference to the component, where .element is protected )
```
@ViewChildren('virtual-scroller')
```

This specifies which type of injectable you want related to the selector.  (In this case the Angular wrapper over the HTMLElement, which has a public property .nativeElement)
```
@ViewChildren('virtual-scroller', { read: ElementRef })
```

Also, Angular 8 requires the new "static" property to be set.
```
@ViewChildren('virtual-scroller', { read: ElementRef, static: false })
```

I didn't test this code, but I believe it will work.

Please re-open if you still can't get what you need.
