### ISSUE TITLE
Support for multiple additional elements in scroll

### ISSUE THREAD

**Issue by lincolnthree** [rintoj/ngx-virtual-scroller#346]
Hello!

First, thank you for this fantastic VS library. I'm trying to work with multiple large groups of nested data, like so:

`{ item1: [1,2,3...N], item2: [9,10,11...N], ... M }`

I'm wondering if there is a good approach to using "nested" virtual scroll in this scenario, where each item contains sub-items. Obviously, the example I show below would result in multiple scroll containers and would not be a pleasant (or possibly at all usable) user experience, but is there an approach that would work in this scenario?

The issue, of course, is that these groups need to be displayed inline, as a large, infinite-scrollable list.

Something like this:

```
<virtual-scroller #scroll [items]="items">
 <div class='item-group-container' *ngFor="let item of scroll.viewPortItems">
  <h1> header stuff </h2>
  <div class='item-list-wrapper>
    <virtual-scroller #scroll2 [items]="item.children">
       <input type="search">
       <div #container>
           <my-custom-component *ngFor="let item of scroll2.viewPortItems">
           </my-custom-component>
       </div>
   </virtual-scroller>
  </div>
 </div>
</virtual-scroller>```

Any thoughts on how this might be possible to achieve? Thanks for your feedback.

**Comment by speige** [comment]
I'm sorry, we don't officially support any feature like this. You can try it out to see if it works, but I'm not sure if it will & we probably won't be able to fix any bugs you find.

I don't have any alternate ideas on how to achieve this off the top of my head. If you're able to figure something out, feel free to submit a pull-request or explanation so future users can read it.

I wonder if you could re-design your app's UI concept so that a nested virtual-scroller isn't necessary? Even if you can make it work how you want, I wonder if it'll be a good user experience?

Anyways, I'm going to close this issue as it's not something we have the resources to help with. Good luck!

**Comment by lincolnthree** [comment]
Ok! Thanks for taking the time to look. I appreciate it!
